project_id = "gdulykjwkrezaidlylyj"

[functions.convert-email-to-deal]
verify_jwt = false

[functions.fetch-email-attachments]
verify_jwt = false

[functions.analyze-document]
verify_jwt = false

[functions.analyze-deal-overview]
verify_jwt = false

[functions.submit-deal]
verify_jwt = false

[functions.fetch-emails]
verify_jwt = false

[functions.send-email]
verify_jwt = false